import "./globals.css";
import { DM_Sans, Raleway } from "next/font/google";

const dmSans = DM_Sans({ subsets: ["latin"], display : "auto", weight: ["400", "500", "700"] });
const raleway = Raleway({ subsets: ["latin"], display :  "fallback", weight: ["100","200","300","400", "500","600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={dmSans.className}>{children}</body>
    </html>
  );
}
